package inf112.roborally.app.tile;

public enum TileType {
    WALL,
    CORNER,
    STOP_WALL,
    HOLE,
    WRENCH,
    YELLOW_CONVEYOR_STRAIGHT,
    YELLOW_CONVEYOR_TURN_LEFT,
    YELLOW_CONVEYOR_TURN_RIGHT,
    YELLOW_CONVEYOR_2_IN_1_OUT_RIGHT,
    YELLOW_CONVEYOR_2_IN_1_OUT_LEFT,
    YELLOW_CONVEYOR_2_IN_1_OUT_UP,
    BLUE_CONVEYOR_STRAIGHT,
    BLUE_CONVEYOR_TURN_LEFT,
    BLUE_CONVEYOR_TURN_RIGHT,
    BLUE_CONVEYOR_2_IN_1_OUT_RIGHT,
    BLUE_CONVEYOR_2_IN_1_OUT_LEFT,
    BLUE_CONVEYOR_2_IN_1_OUT_UP,

}
